config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'events#index'
  resources :events
  resources :users, only: [:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :new_participant_send

  def new_participant_send
    UserMailer.new_participant_email(self).deliver_now
  end

  belongs_to :participant, class_name: "User"
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  validates :start_date, presence: true
  validate :in_the_future?
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0}
  validate :multiple_of_5?
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true,  in: 1..1000}
  validates :location, presence: true

    
  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :participants, through: :attendances

  def end_date
    date = self.start_date + self.duration*60
    return date.strftime("%d/%m/%y à %H:%M")
  end

  def get_month
    month = ["", "JANV.", "FEV.", "MARS", "AVR.", "MAI", "JUIN", "JUIL.", "AOUT", "SEPT.", "OCT.", "NOV.", "DEC."]
    return month[self.start_date.month]
  end

  def short_description
    if self.description.length < 80
      return self.description
    else
      return self.description[0..80] + "..."
    end
  end

  def convert_start_date
    return self.start_date.strftime("%d/%m/%y à %H:%M")
  end

  def can_participate?(user)
    return !(user == nil || user == self.admin || self.participants.include?(user))
  end

  def participate?(user)
    return self.participants.include?(user)
  end

  private

  def multiple_of_5?
  	#return self.duration % 5 == 0
  	if self.duration.present? && self.duration % 5 != 0
        errors.add(:duration, "must be multiple of 5")
    end
  end

  def in_the_future?
  	#return self.start_date > Time.now
  	if self.start_date.present? && self.start_date < Time.now
        errors.add(:start_date, "can't be in the past")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def name
  	return "#{first_name} #{last_name}"
  end
  
  has_many :organized_events, foreign_key: 'admin_id', class_name: "Event", dependent: :destroy
  has_many :attendances, foreign_key: 'participant_id', dependent: :destroy
  has_many :events, through: :attendances
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :redirect_to_root, if: :not_admin?, only: [:edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    # @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.admin = current_user

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit
    @event = Event.new
  end

  def update
    @event = Event.new(event_params)
    @event.admin = current_user

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
  end

  def not_admin?
    return @event.admin != current_user
  end

  def redirect_to_root
    redirect_to events_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show]
  before_action :redirect_to_root, if: :not_current_user_profile?, only: [:show]


  #after_create :send_email

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :encrypted_password, :description, :first_name, :last_name)
    end

    def not_current_user_profile?
      return params[:id].to_i != current_user.id
    end

    def redirect_to_root
      redirect_to events_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_with(model: event, local: true) do |f| %>
        <% if event.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
            <% event.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, autocomplete: "title", class: "form-control", placeholder:"Titre", required: true %>
        </div>



        <div class="form-group">
         <%= f.label :start_date %>
         <%= f.datetime_local_field :start_date , class: "form-control", min:"1000-01-01", max:"3000-12-31" %>
        </div>


        <div class="form-group">
          <%= f.label :duration %>
          <%= f.number_field :duration, class: "form-control", placeholder:"Durée (en minutes)", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :price %>
          <%= f.number_field :price, class: "form-control", placeholder:"Prix (€)", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :location %>
          <%= f.text_field :location, class: "form-control", placeholder:"Lieu", required: true %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class: "form-control", placeholder:"Description", required: true %>
        </div>
        
        <div class="actions mt-5">
          <%= f.submit "Créer", class: "btn btn-lg btn-primary btn-block" %>
        </div>
        <br>
        <%= link_to 'Annuler', events_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<br><br>
<h1 class="h3 mb-3 font-weight-normal text-center">Modifier un évenement</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="jumbotron" style="background-image: url(https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?cs=srgb&dl=audience-band-concert-1105666.jpg&fm=jpg); background-size: 100%;">

  <div class="container">
    <h1 class="display-3" style="color: white;">Vivez le meilleur!</h1>
    <p style="color: white;">Ne ratez plus un évenement près de chez vous.</p>
  </div>
</div>

<section class="card-events">
  <div class="row">
    <% Event.all.each do |event| %>
      <%= render 'shared/event-card', event: event %>
    <% end %>
  </div>

</section>

app/views/events/new.html.erb
<br><br>
<h1 class="h3 mb-3 font-weight-normal text-center">Créer un évenement</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<div class="jumbotron" style="background-image: url(https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg?cs=srgb&dl=audience-band-concert-1105666.jpg&fm=jpg); background-size: 100%;">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 col-md-10 offset-md-1">
        <section class="card frame">
          <div class="card-body">
            <h5 class="card-title">
              <strong><%= @event.title %></strong>
            </h5>

            <p><i class="fas fa-map-marker-alt text-warning"></i>  <%= @event.location %></p>
            <p>Créé par <em><%= @event.admin.name %></em> <%= @event.admin.email %> </p>
            <p><%= @event.participants.count %> personnes participent à cet évenement </p>
            <p>
              début : <%= @event.convert_start_date %>
            </p>
            <p>
              fin : <%= @event.end_date %>
            </p>

            <p class="price rounded-circle position-absolute border border-info text-light"><strong><%= @event.price %>€</strong></p>
            <aside class="date position-absolute">
                  <p class="month text-warning position-absolute w-100"><strong><%= @event.get_month %></strong></p>
                  <p class="day_of_month position-absolute w-100"><%= @event.start_date.day %></p>
            </aside>
            

            <div class="container bg-light border border-info rounded">
              <p><strong>Description:</strong></p>
              <p><%= @event.description %></p>
            </div>



            <%= link_to 'Edit', edit_event_path(@event) %> |
            <%= link_to 'Back', events_path %>

          </div>
        </section>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Events Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>




<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<script src="https://kit.fontawesome.com/75bdcd3995.js"></script>


  </head>

  <body class="bg-light">



    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "The Events Project", events_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Accueil", events_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Créer un nouvel évenement", new_event_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if !user_signed_in? %>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                S'inscrire / Se connecter <%= current_user %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "S'inscrire", new_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Se connecter", new_user_session_path, class: "dropdown-item" %>
              </div>
            <% else %>
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Mon profil
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Mon profil", user_path(current_user), class: "dropdown-item" %>
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            <% end %>
          </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button> -->
    </form>
      </div>
    </nav>











    <%= yield %>
  </body>

</html>

app/views/shared/_event-card.html.erb
<div class="col-sm-6 col-md-4 col-lg-3">
    <div class="card event-card w-100">     
        <div class="card-body">
            <br>
          	<h5 class="card-title"><%= event.title %></h5>
          	<p class="card-text"><%= event.short_description %></p>
          	<p class="card-text">Le : <%= event.convert_start_date %></p>
          	<aside class="price rounded-circle position-absolute border border-info text-light">
            	<p class="card-text"><strong><%= event.price %>€</strong></p>
          	</aside>
            <aside class="date position-absolute">
              <p class="month text-warning position-absolute w-100"><strong><%= event.get_month %></strong></p>
              <p class="day_of_month position-absolute w-100"><%= event.start_date.day %></p>
            </aside>
        	<p class="card-text"><i class="fas fa-map-marker-alt text-warning"></i> <%= event.location %></p>
          <%= link_to "", event_path(event), class:"stretched-link" %>
    	</div>
	</div>
</div>

app/views/users/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_with(model: user, local: true) do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Modifier les informations</h1>
        <% if user.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

            <ul>
            <% user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group">
          <%= f.label :description, "Description" %><br />
          <%= f.text_area :description, autofocus: true, autocomplete: "description", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, autocomplete: "Prenom", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :last_name %>
          <%= f.text_field :last_name, autocomplete: "Nom", class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Mettre à jour", class: "btn btn-lg btn-primary btn-block" %>
        </div>
        <br>
        <%= link_to 'Annuler', @user %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<br>
<section class="card-events">
  <h2>Mes infos</h2>
  <div class="row">
    <div class="col">
    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @user.description %>
    </p>

    <p>
      <strong>First name:</strong>
      <%= @user.first_name %>
    </p>

    <p>
      <strong>Last name:</strong>
      <%= @user.last_name %>
    </p>

    <%= link_to 'Edit', edit_user_path(@user) %> |


      <%= link_to "Edit email / password", edit_user_registration_path %>


  </div>
  </div>
</section>
<br>



<section class="card-events">
  <h2>Mes évenements</h2>
  <div class="row">
    <% @user.organized_events.each do |event| %>
      <%= render 'shared/event-card', event: event %>
    <% end %>
  </div>